# Generated by Django 3.0.2 on 2020-01-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Proveedor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clintes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=10)),
                ('Saldo', models.IntegerField()),
                ('UltimoAbono', models.DateField()),
                ('Zona', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=20)),
                ('Empresa', models.CharField(max_length=20)),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
